vich_uploader:
    db_driver: orm
    form: true
    mappings:
        gra_miniaturka:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        gra_galeria:
            uri_prefix: 'uploads/files/gallery/'
            upload_destination: '%kernel.project_dir%/public/uploads/files/gallery/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
